// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ODWNVLyaJuRm-NRNcqT3QiGa8eCcREU',
    appId: '1:516219438323:web:b57f78182cbe53bdc0e386',
    messagingSenderId: '516219438323',
    projectId: 'what2eat-450a9',
    authDomain: 'what2eat-450a9.firebaseapp.com',
    storageBucket: 'what2eat-450a9.firebasestorage.app',
    measurementId: 'G-XK4FMCGB1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsWjONeQYM7rFHLKD3MSh3qlLFhy4rD4',
    appId: '1:516219438323:android:6f8c128be3c689bfc0e386',
    messagingSenderId: '516219438323',
    projectId: 'what2eat-450a9',
    storageBucket: 'what2eat-450a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2olaXfXyRqOzNrCAUHHxrR0Hv4NCukc',
    appId: '1:516219438323:ios:5d06817a296e436ac0e386',
    messagingSenderId: '516219438323',
    projectId: 'what2eat-450a9',
    storageBucket: 'what2eat-450a9.firebasestorage.app',
    iosBundleId: 'com.example.what2eat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2olaXfXyRqOzNrCAUHHxrR0Hv4NCukc',
    appId: '1:516219438323:ios:5d06817a296e436ac0e386',
    messagingSenderId: '516219438323',
    projectId: 'what2eat-450a9',
    storageBucket: 'what2eat-450a9.firebasestorage.app',
    iosBundleId: 'com.example.what2eat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ODWNVLyaJuRm-NRNcqT3QiGa8eCcREU',
    appId: '1:516219438323:web:abd72a77ee0f4e59c0e386',
    messagingSenderId: '516219438323',
    projectId: 'what2eat-450a9',
    authDomain: 'what2eat-450a9.firebaseapp.com',
    storageBucket: 'what2eat-450a9.firebasestorage.app',
    measurementId: 'G-W4H1PVBSHH',
  );

}